Is this code correct for the below acceptance criteria

from util.logging_util import LOGGER
from service.managed_accounts_service import ManagedAccountsService


class ManagedAccountValidation:
    @staticmethod
    def validating_account_managed(answer_file, stp_data):
        account_Id = answer_file['brokerageAccount']['accountId']
        response_data = ManagedAccountsService.retrieve_managed_accounts(account_Id)
        if response_data[0].get('accountManagementType') == 'MANAGED':
            if response_data is None:
                stp_data['is_stp_eligible'] = False
                stp_data['message'] = stp_data['message'] + "\nUnable to determine account type due to service failure. Moving on to the next validation."
                LOGGER.info('Unable to determine account type due to service failure. Moving on to the next validation. , set message: ' + stp_data['message'])
            else:
                stp_data['is_stp_eligible'] = False
                stp_data['message'] = stp_data['message'] + "\nVanguard Account is Managed. STP Automation is out of scope. Sending to Manual Queue."
                LOGGER.info('Vanguard Account is Managed. STP Automation is out of scope. Sending to Manual Queue. , set message: ' + stp_data['message'])
        else:
            LOGGER.info("Vanguard Account is not Managed. Continuing to the next validation.")




Acceptance Criteria

Given the account listed in the answer file is NOT a managed account

And the service call is successful

And managed account data is returned for the given client/account

When the lambda validates the account is not managed

Then it logs a message (temporary)

And continues on to the next step

 

Given the account listed in the answer file is a managed account

And the service call is successful

And account data is returned for the given account

When the lambda validates the account

Then it logs a message (temporary)

and sets  STP flag to false

and moves on to the next validation

 

Given the account listed in the answer file is a managed account

And the service call is NOT successful

And account data is none

When the lambda validates the account

Then it logs a message (temporary)

and sets  STP flag to false

and moves on to the next validation
